title: Shian Chang
logo: /photo.jpg

description: "Personal academic website of Shian Chang, PhD Candidate in Economics at National Taiwan University."

position: PhD Candidate
affiliation: National Taiwan University
department: Department of Economics

email: D10323001@ntu.edu.tw

#google_scholar: "https://scholar.google.com/citations?hl=en&user=L-9VYcgAAAAJ"

theme: jekyll-theme-minimal
