title: Shian Chang
logo: /photo.png

description: "Personal academic website of Shian Chang, PhD Candidate in Economics at National Taiwan University."

position: PhD Candidate
affiliation: National Taiwan University
department: Department of Economics

email: D10323001@ntu.edu.tw

google_scholar: "https://scholar.google.com/citations?hl=en&user=L-9VYcgAAAAJ"
linkedin: "https://www.linkedin.com/in/%E7%BF%94-%E5%BC%B5-a3483220b/"
github_url: "https://github.com/shian-chang-econ"

theme: jekyll-theme-minimal
